# generated by datamodel-codegen:
#   filename:  tmpgpdepxfe.json
#   timestamp: 2026-04-09T19:34:26+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class ApiKeyCreateResponse(BaseModel):
    contexts: list[str] | None = Field(
        None, description='Allowed contexts', title='Contexts'
    )
    expires_at: str = Field(
        ..., description='ISO 8601 expiration timestamp', title='Expires At'
    )
    key_id: str = Field(..., description='Key identifier', title='Key Id')
    role: str = Field(..., description='Assigned role', title='Role')
    token: str = Field(..., description='JWT token (shown once)', title='Token')


class ApiKeyListItem(BaseModel):
    contexts: list[str] | None = Field(
        None, description='Allowed contexts', title='Contexts'
    )
    created_at: str = Field(
        ..., description='ISO 8601 creation timestamp', title='Created At'
    )
    created_by: str = Field(..., description='Creator identity', title='Created By')
    expires_at: str = Field(
        ..., description='ISO 8601 expiration timestamp', title='Expires At'
    )
    key_id: str = Field(..., description='Key identifier', title='Key Id')
    role: str = Field(..., description='Assigned role', title='Role')


class ContextInfo(BaseModel):
    name: str = Field(..., description='Context name', title='Name')
    queue_depth: int = Field(
        ..., description='Number of jobs currently queued', title='Queue Depth'
    )
    workers: int = Field(
        ...,
        description='Number of active workers serving this context',
        title='Workers',
    )


class FailedJobSummary(BaseModel):
    error: str | None = Field(
        None, description='Sanitized error message', title='Error'
    )
    failed_at: str | None = Field(
        None, description='ISO 8601 failure timestamp', title='Failed At'
    )
    func: str | None = Field('', description='Worker function name', title='Func')
    host: str | None = Field('', description='Target device host', title='Host')
    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    platform: str | None = Field('', description='Netmiko platform', title='Platform')
    port: int | None = Field(22, description='SSH port', title='Port')


class HealthComponentStatus(BaseModel):
    status: str = Field(
        ...,
        description='Component status (healthy, unhealthy, no_workers)',
        title='Status',
    )


class QueueHealth(BaseModel):
    depth: int | None = Field(0, description='Number of jobs in queue', title='Depth')
    status: str = Field(
        ...,
        description='Component status (healthy, unhealthy, no_workers)',
        title='Status',
    )


class WorkersHealth(BaseModel):
    active_jobs: int | None = Field(
        0, description='Jobs currently processing', title='Active Jobs'
    )
    count: int | None = Field(
        0, description='Number of worker pods/hosts', title='Count'
    )
    status: str = Field(
        ...,
        description='Component status (healthy, unhealthy, no_workers)',
        title='Status',
    )


class JobResponse(BaseModel):
    deduplicated: bool | None = Field(
        False,
        description='True if this response reuses an in-flight duplicate job',
        title='Deduplicated',
    )
    enqueued_at: str = Field(
        ..., description='ISO 8601 timestamp when job was enqueued', title='Enqueued At'
    )
    idempotent: bool | None = Field(
        False,
        description='True if this response reuses an existing job',
        title='Idempotent',
    )
    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    message: str = Field(..., description='Status message', title='Message')
    queue_position: int = Field(
        ...,
        description='Approximate position in queue (1 = next to run)',
        title='Queue Position',
    )
    timeout: int = Field(..., description='Job timeout in seconds', title='Timeout')


class JobResultResponse(BaseModel):
    detected_platform: str | None = Field(None, title='Detected Platform')
    error: str | None = Field(None, title='Error')
    job_id: str = Field(..., title='Job Id')
    results: Any = Field(None, title='Results')
    status: str = Field(..., title='Status')
    tags: dict[str, str] | None = Field(None, title='Tags')


class Status(StrEnum):
    FINISHED = 'finished'
    FAILED = 'failed'
    STARTED = 'started'
    QUEUED = 'queued'


class ListJobsQuery(BaseModel):
    page: int | None = Field(1, ge=1, title='Page')
    per_page: int | None = Field(20, ge=1, le=100, title='Per Page')
    status: Status | None = Field(None, title='Status')
    tag: str | None = Field(
        None, description="Filter by tag in 'key:value' format", title='Tag'
    )


class JobSummary(BaseModel):
    created_at: str | None = Field(
        None, description='ISO 8601 creation timestamp', title='Created At'
    )
    ended_at: str | None = Field(
        None, description='ISO 8601 completion timestamp', title='Ended At'
    )
    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    status: str = Field(..., description='Job status', title='Status')
    tags: dict[str, str] | None = Field(
        None, description='Job metadata tags', title='Tags'
    )


class PaginationInfo(BaseModel):
    page: int = Field(..., description='Current page number', title='Page')
    pages: int = Field(..., description='Total number of pages', title='Pages')
    per_page: int = Field(..., description='Results per page', title='Per Page')
    total: int = Field(..., description='Total number of results', title='Total')


class SendCommandRequest(BaseModel):
    commands: list[str] = Field(
        ..., description='Commands to execute', min_length=1, title='Commands'
    )
    conn_timeout: float | None = Field(
        10.0,
        description='TCP connection timeout in seconds',
        ge=1.0,
        title='Conn Timeout',
    )
    context: str | None = Field(
        'default',
        description="Routing context for multi-segment environments (e.g. 'corp', 'oob-dc1', 'hk-prod')",
        title='Context',
    )
    device_type: str | None = Field(
        None,
        description='Deprecated: use platform instead (v1 compat)',
        title='Device Type',
    )
    enable: str | None = Field(
        None,
        description='Enable password (optional, defaults to password)',
        title='Enable',
    )
    expect_string: str | None = Field(
        None,
        description='Regex pattern to match in device output (overrides prompt detection)',
        title='Expect String',
    )
    host: str | None = Field(
        None, description='Device IP address or hostname', title='Host'
    )
    ip: str | None = Field(
        None, description='Deprecated: use host instead (v1 compat)', title='Ip'
    )
    password: str | None = Field(
        None,
        description='Device password (required for API key auth)',
        title='Password',
    )
    platform: str | None = Field(
        'cisco_ios',
        description="Netmiko device type (use 'autodetect' for SSHDetect)",
        title='Platform',
    )
    port: int | None = Field(22, description='SSH port', ge=1, le=65535, title='Port')
    read_timeout: float | None = Field(
        30.0,
        description='Read timeout in seconds for device responses',
        ge=1.0,
        title='Read Timeout',
    )
    tags: dict[str, str] | None = Field(
        None,
        description='Optional key-value metadata tags (max 10, keys/values max 64 chars, alphanumeric + hyphens/underscores/colons)',
        title='Tags',
    )
    username: str | None = Field(
        None,
        description='Device username (required for API key auth)',
        title='Username',
    )
    webhook_secret: str | None = Field(
        None,
        description='Optional shared secret for HMAC-SHA256 webhook payload signing',
        title='Webhook Secret',
    )
    webhook_url: str | None = Field(
        None,
        description='Optional HTTPS URL to POST a job completion notification to (never includes results)',
        title='Webhook Url',
    )


class SendCommandStructuredRequest(BaseModel):
    commands: list[str] = Field(
        ..., description='Commands to execute', min_length=1, title='Commands'
    )
    conn_timeout: float | None = Field(
        10.0,
        description='TCP connection timeout in seconds',
        ge=1.0,
        title='Conn Timeout',
    )
    context: str | None = Field(
        'default',
        description="Routing context for multi-segment environments (e.g. 'corp', 'oob-dc1', 'hk-prod')",
        title='Context',
    )
    device_type: str | None = Field(
        None,
        description='Deprecated: use platform instead (v1 compat)',
        title='Device Type',
    )
    enable: str | None = Field(
        None,
        description='Enable password (optional, defaults to password)',
        title='Enable',
    )
    host: str | None = Field(
        None, description='Device IP address or hostname', title='Host'
    )
    ip: str | None = Field(
        None, description='Deprecated: use host instead (v1 compat)', title='Ip'
    )
    password: str | None = Field(
        None,
        description='Device password (required for API key auth)',
        title='Password',
    )
    platform: str | None = Field(
        'cisco_ios',
        description="Netmiko device type (use 'autodetect' for SSHDetect)",
        title='Platform',
    )
    port: int | None = Field(22, description='SSH port', ge=1, le=65535, title='Port')
    read_timeout: float | None = Field(
        30.0,
        description='Read timeout in seconds for device responses',
        ge=1.0,
        title='Read Timeout',
    )
    tags: dict[str, str] | None = Field(
        None,
        description='Optional key-value metadata tags (max 10, keys/values max 64 chars, alphanumeric + hyphens/underscores/colons)',
        title='Tags',
    )
    textfsm_template: str | None = Field(
        None,
        description='Custom TextFSM template (uses ntc-templates if not provided)',
        title='Textfsm Template',
    )
    ttp_template: str | None = Field(
        None,
        description='TTP template string or ttp://<path> reference (mutually exclusive with textfsm_template)',
        title='Ttp Template',
    )
    username: str | None = Field(
        None,
        description='Device username (required for API key auth)',
        title='Username',
    )
    webhook_secret: str | None = Field(
        None,
        description='Optional shared secret for HMAC-SHA256 webhook payload signing',
        title='Webhook Secret',
    )
    webhook_url: str | None = Field(
        None,
        description='Optional HTTPS URL to POST a job completion notification to (never includes results)',
        title='Webhook Url',
    )


class Commands(RootModel[list[str]]):
    root: list[str] = Field(
        None,
        description='Configuration commands (alias)',
        min_length=1,
        title='Commands',
    )


class Config(RootModel[list[str]]):
    root: list[str] = Field(
        None, description='Configuration commands', min_length=1, title='Config'
    )


class SendConfigRequest(BaseModel):
    commands: Commands | None = Field(
        None, description='Configuration commands (alias)', title='Commands'
    )
    commit: bool | None = Field(
        False, description='Commit configuration (Juniper)', title='Commit'
    )
    config: Config | None = Field(
        None, description='Configuration commands', title='Config'
    )
    conn_timeout: float | None = Field(
        10.0,
        description='TCP connection timeout in seconds',
        ge=1.0,
        title='Conn Timeout',
    )
    context: str | None = Field(
        'default',
        description='Routing context for multi-segment environments',
        title='Context',
    )
    device_type: str | None = Field(
        None,
        description='Deprecated: use platform instead (v1 compat)',
        title='Device Type',
    )
    enable: str | None = Field(
        None,
        description='Enable password (optional, defaults to password)',
        title='Enable',
    )
    host: str | None = Field(
        None, description='Device IP address or hostname', title='Host'
    )
    ip: str | None = Field(
        None, description='Deprecated: use host instead (v1 compat)', title='Ip'
    )
    password: str | None = Field(
        None,
        description='Device password (required for API key auth)',
        title='Password',
    )
    platform: str | None = Field(
        'cisco_ios',
        description="Netmiko device type (use 'autodetect' for SSHDetect)",
        title='Platform',
    )
    port: int | None = Field(22, description='SSH port', ge=1, le=65535, title='Port')
    read_timeout: float | None = Field(
        30.0,
        description='Read timeout in seconds for device responses',
        ge=1.0,
        title='Read Timeout',
    )
    save_config: bool | None = Field(
        False, description='Save configuration after applying', title='Save Config'
    )
    tags: dict[str, str] | None = Field(
        None,
        description='Optional key-value metadata tags (max 10, keys/values max 64 chars)',
        title='Tags',
    )
    username: str | None = Field(
        None,
        description='Device username (required for API key auth)',
        title='Username',
    )
    webhook_secret: str | None = Field(
        None,
        description='Optional shared secret for HMAC-SHA256 webhook payload signing',
        title='Webhook Secret',
    )
    webhook_url: str | None = Field(
        None,
        description='Optional HTTPS URL to POST a job completion notification to (never includes results)',
        title='Webhook Url',
    )


class ValidationErrorElement(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Error context')
    loc: list[str] = Field(..., title='Missing field name')
    msg: str = Field(..., title='Error message')
    type: str = Field(..., title='Error type')


class ApiKeyListResponse(BaseModel):
    keys: list[ApiKeyListItem] = Field(..., description='Active API keys', title='Keys')


class ContextsResponse(BaseModel):
    contexts: list[ContextInfo] = Field(
        ..., description='Active contexts', title='Contexts'
    )


class FailedJobsResponse(BaseModel):
    jobs: list[FailedJobSummary] = Field(
        ..., description='List of failed jobs', title='Jobs'
    )
    total: int = Field(..., description='Total number of failed jobs', title='Total')


class HealthComponents(BaseModel):
    failed_jobs: int | None = Field(
        0, description='Number of failed jobs', title='Failed Jobs'
    )
    queue: QueueHealth = Field(..., description='Job queue status')
    redis: HealthComponentStatus = Field(..., description='Redis connectivity')
    workers: WorkersHealth = Field(..., description='Worker pool status')


class ListJobsResponse(BaseModel):
    jobs: list[JobSummary] = Field(..., description='List of jobs', title='Jobs')
    pagination: PaginationInfo = Field(..., description='Pagination metadata')


class ValidationError(RootModel[list[ValidationErrorElement]]):
    root: list[ValidationErrorElement] = Field(
        ...,
        description='Model of a validation error response.',
        title='ValidationError',
    )


class HealthCheckResponse(BaseModel):
    components: HealthComponents = Field(..., description='Component health details')
    status: str = Field(
        ...,
        description='Overall status: healthy, degraded, or no_workers',
        title='Status',
    )
    uptime_seconds: int = Field(
        ..., description='Seconds since API start', title='Uptime Seconds'
    )
    version: str = Field(..., description='NAAS version', title='Version')
