apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: naas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - --requirepass
            - $(REDIS_PASSWORD)
            - --port
            - "6379"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: naas-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
