apiVersion: v1
kind: Service
metadata:
  name: naas-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
    app: naas-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: naas-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.port }}
