{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: naas-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- if .Values.secrets.encryptionKey }}
  NAAS_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  NAAS_JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.tlsCert }}
  NAAS_CERT: {{ .Values.secrets.tlsCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.tlsKey }}
  NAAS_KEY: {{ .Values.secrets.tlsKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.tlsCaBundle }}
  NAAS_CA_BUNDLE: {{ .Values.secrets.tlsCaBundle | b64enc | quote }}
  {{- end }}
{{- end }}
